server {
    listen 80;
    server_name _;

    # Serve the dashboard UI from the NGINX html folder
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy to receiver
    location /receiver {
        proxy_pass http://receiver:8080;
        proxy_set_header Host $host; # Tells the backend microservice the original domain name the client requested
        proxy_set_header X-Real-IP $remote_addr; # Passes the actual IP address of the user making the request
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Appends the client's IP to a list
        proxy_set_header X-Forwarded-Proto $scheme; # Tells the backend whether the original request was made over HTTP or HTTPS
    }

    # Reverse proxy to processing
    location /processing {
        proxy_pass http://processing:8100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Reverse proxy to analyzer
    location /analyzer {
        proxy_pass http://analyzer:8110;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # UI also calls the health service
    location /health {
        proxy_pass http://health:8120;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}